name: build windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: powershell -File .\build_windows.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: trktor.exe
          path: ${{ github.workspace }}/dist/
