name: build linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash build_linux.sh
      - uses: actions/upload-artifact@v3
        with:
          name: trktor.x86_64
          path: ${{ github.workspace }}/dist/
